---
- name: 安装和配置Nginx服务器
  hosts: ubuntu_servers
  become: yes
  become_method: sudo
  
  tasks:
    # 任务1：创建应用目录
    - name: 创建 /opt/myapp 目录
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'
      tags: directory
    
    # 任务2：安装Nginx
    - name: 更新apt软件包缓存
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: install
    
    - name: 安装Nginx软件包
      apt:
        name: nginx
        state: present
      tags: install
    
    # 任务3：启动Nginx服务
    - name: 启动Nginx服务
      service:
        name: nginx
        state: started
        enabled: yes
      tags: service
    
    # 任务4：验证安装
    - name: 获取Nginx版本信息
      command: nginx -v
      register: nginx_version
      changed_when: false
      tags: verify
    
    - name: 显示安装成功信息
      debug:
        msg: "Nginx安装成功！版本：{{ nginx_version.stdout }}"
      tags: verify
